[project]
name = "Beatrice_app"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "yoonsen", email = "yoonsen@gmail.com"},
]
dependencies = []
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
